import java.util.UUID;

/**
* A class that register a parcel with a sender and a recipient that is
* associated with the parcel.
* The parcel also gets a barcode that is random generated by java.util.UUID.
*
* @author Philip Hoang
*/

public class Parcel {
  private Person sender;
  private Person recipient;
  private UUID barcode;

  /**
  * Register a parcel
  * @param  Person sender        a person object that is the sender
  * @param  Person recipient     a person object that is the recipient
  * @return a new parcel object
  */
  public Parcel(Person sender, Person recipient) {
    this.sender = sender;
    this.recipient = recipient;

    //This method prints out a random barcode
    this.barcode = UUID.randomUUID();
  }

  /**
  * Prints out an information of the parcel.
  * Information are barcode, a sender and a recipient.
  *
  * @return a string that contains the information of the parcel
  */
  public String toString() {
    String s = "";
    s = "Barcode: " + barcode + "\n"
        + "Sender: " + sender + "\n"
        + "Recipient: " + recipient;

    return s;
  }


}
